### ISSUE TITLE
Maintenance - Unknown column 'deleteAfterHours'

### ISSUE THREAD

**Issue by palazzetti** [elements-at/ProcessManager#64]
Pimcore version: 6.8.3
ProcessManager version: 3.0.35
After running `bin/console process-manager:maintenance`
<img width="987" alt="image" src="https://user-images.githubusercontent.com/49283657/96570126-42e61200-12ca-11eb-85f6-bb1fd746510d.png">

**Comment by ckogler-elements** [comment]
Hi,
i think you have to execute the migrations. Please take a look at https://github.com/elements-at/ProcessManager/issues/62 .
This should fix it.

Regards,
Christian

**Comment by palazzetti** [comment]
You are right, I just looked inside the code and it seems like the line https://github.com/elements-at/ProcessManager/blob/144aa4d2deddd0f9adffbbb201d0cfe363bca621/src/Migrations/Version00000015.php#L21 has not been executed

**Comment by palazzetti** [comment]
Also, running `bin/console pimcore:bundle:update ElementsProcessManagerBundle` causes 
![image](https://user-images.githubusercontent.com/49283657/96571022-53e35300-12cb-11eb-8d37-bad1d0e710ec.png)

**Comment by palazzetti** [comment]
@ckogler-elements I managed to run the migration `Version00000015` manually but what about the others? 
I am still experiencing the issue above, could you help me?

> Also, running `bin/console pimcore:bundle:update ElementsProcessManagerBundle` causes
> ![image](https://user-images.githubusercontent.com/49283657/96571022-53e35300-12cb-11eb-8d37-bad1d0e710ec.png)

**Comment by ckogler-elements** [comment]
Hi,
bin/console pimcore:bundle:update ElementsProcessManagerBundle should run through without any error normaly. The error above seems to come directly from Picmore. The ProcessManager Bundle doesn't do anything with objects.

Did you also made a pimcore update? 

./bin/console pimcore:migrations:migrate -s pimcore_core
./bin/console cache:clear

may help. 
If the above dosn't work. Maybe a
 ./bin/console  pimcore:deployment:classes-rebuild 
could fix the issue.

Regards,
Christian

**Comment by palazzetti** [comment]
> Hi,
> bin/console pimcore:bundle:update ElementsProcessManagerBundle should run through without any error normaly. The error above seems to come directly from Picmore. The ProcessManager Bundle doesn't do anything with objects.
> 
> Did you also made a pimcore update?
> 
> ./bin/console pimcore:migrations:migrate -s pimcore_core
> ./bin/console cache:clear
> 
> may help.
> If the above dosn't work. Maybe a
> ./bin/console pimcore:deployment:classes-rebuild
> could fix the issue.
> 
> Regards,
> Christian

No changes, I suppose I'll be stuck with Version00000015.
Is there any way to run the other classes manually?
Thanks for the help

**Comment by ckogler-elements** [comment]
bin/console pimcore:migrations:migrate 00000016 --bundle=ElementsProcessManagerBundle
bin/console pimcore:migrations:migrate 00000017 --bundle=ElementsProcessManagerBundle
bin/console pimcore:migrations:migrate 00000018 --bundle=ElementsProcessManagerBundle

Would execute to the single Versions.

**Comment by palazzetti** [comment]
> bin/console pimcore:migrations:migrate 00000016 --bundle=ElementsProcessManagerBundle

Actually, no changes 🤣 
Thanks for the try, what could I ask to Pimcore devs?
<img width="997" alt="Schermata 2020-10-20 alle 14 28 08" src="https://user-images.githubusercontent.com/49283657/96585940-8f3c4c80-12e0-11eb-95b9-cebbd3b65717.png">

**Comment by ckogler-elements** [comment]
Well, you can ask them why it wants to update a objects table, if the bundle doesn't use any Pimcore objects... just link to this issue... Really strange.

Last try would be to delete the object_localized_query_10_es_es table because its just a view and it should be created automatically then. 

Regards,
Christian

**Comment by palazzetti** [comment]
> Well, you can ask them why it wants to update a objects table, if the bundle doesn't use any Pimcore objects... just link to this issue... Really strange.
> 
> Last try would be to delete the object_localized_query_10_es_es table because its just a view and it should be created automatically then.
> 
> Regards,
> Christian

Ok thanks, btw I already tried removing those tables and the result doesn't change, I need to drop like 10 tables eventually and I don't fill very confident doing it.
I'll create a new issue and link it to this, thanks 💭
